version: "3.9"

services:
  ethers-node-js:
    container_name: ethers-node-js
    restart: always
    build:
      context: ./
      target: production
    image: ethers-node-js:1.0.1
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      DB_HOST: mongodb
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
